### ISSUE TITLE
revise: the random name generator needs to use unique names only

### ISSUE THREAD

**Issue by claymcleod** [stjude-rust-labs/crankshaft#2]
I'm talking about [this](https://github.com/stjude-rust-labs/crankshaft/blob/main/crankshaft-engine/src/service/name.rs#L25)—we need to make sure that the names are truly unique and never conflict. One way to do this while minimizing the memory required is to use a [bloom filter](https://docs.rs/bloomfilter/latest/bloomfilter/) and retry generation when a conflict is found. Note that you _definitely_ don't want to keep track of every name (too much memory required).

**Comment by BradenEverson** [comment]
I'd like to take on this issue. So looking into the bloom filter it's pretty much a hashset that only stores whether that hash has or hasn't been stored already? While also using a bitvec to keep it super space efficient? Neat

**Comment by claymcleod** [comment]
Great! Yeah it's a really cool data structure: the key is that false negatives are not possible, but false positives are _slightly_ possible. That being said, in this case, the cost of a false positive is essentially just to do regeneration another time, so it's not a big deal.

I also am going to want to use this service for another (related) project, so it would be great to make it more standalone and "exportable" so to speak. By that, I just mean that it should be written to be consumed by external crates.

One last optimization I would do: I haven't checked thoroughly, but I believe it's relatively expensive to get a thread RNG, so I think what should happen is this should have an internal list of randomly generated IDs that are generated in batch. 

So, for example, you might initialize the data structure with a vector of length 4096: the first time you call for an id, it's empty, so the data structure would hydrate all 4096 ids and give you back the first. The second time, it would recognize that there are still ids in the vector, so it'd give you the second. This would continue until you consume the last id, at which point it would rehydrate the vec.

**Comment by claymcleod** [comment]
Closed by #3
